LOG_CONF_PATH = 'cfg/logging/log.conf'
APP_CONF_ROOT = 'cfg/data_pipeline_app'
INGEST_CONF_SUBPATH = '01_ingestion'
INGEST_SRC_TO_TGT_CONF_SUBPATH = 'src_to_target.yml'
INGEST_SRC_DATA_VALIDATION_CONF_SUBPATH = 'src_data_validation.yml'
TRANSFORM_CONF_SUBPATH = '02_transformation'
DISTRIBUTE_CONF_SUBPATH = '03_distribution'