- dataset_name: dataset1
  path: data/raw/dataset1
  src:
    connector: local_file
    file_type: parquet
  target:
    connector: postgres
    conn_id: DEFAULT
    concurrent_conns: 10
    batch_size: 10000